[package]
name = "oran"
version = "0.1.0"
authors = ["shu nakanishi <shu845@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
lazy_static = "1.2.0"
num-traits = "0.2"
num-derive = "0.3"
colored = "1.6"
clap = "2.32.0"
ordered-float = "1.0.2"
#llvm-sys = "80"
