[package]
name = "oran"
version = "0.1.0"
authors = ["lechatthecat <shu845@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
jemallocator = "0.3.2"
llvm-sys = "80"
