[package]
name = "oran"
version = "0.1.0"
authors = ["lechatthecat <shu845@gmail.com>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plex = "0.2.5"
llvm-sys = "80"
